
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Feb 06 23:15:46 CET 2020
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Else = 10;
  public static final int C_par = 22;
  public static final int Out = 14;
  public static final int Numero = 4;
  public static final int Op_booleano = 25;
  public static final int A_llave = 23;
  public static final int ERROR = 27;
  public static final int Tipo = 2;
  public static final int Const = 11;
  public static final int PuntoYComa = 20;
  public static final int Coma = 18;
  public static final int Op_aritmetico = 5;
  public static final int Op_relacional = 7;
  public static final int In = 13;
  public static final int Main = 15;
  public static final int EOF = 0;
  public static final int C_llave = 24;
  public static final int If = 12;
  public static final int Return = 17;
  public static final int error = 1;
  public static final int Id = 3;
  public static final int Op_logico = 6;
  public static final int A_par = 21;
  public static final int Void = 19;
  public static final int Igual = 9;
  public static final int Def = 16;
  public static final int While = 8;
  public static final int String = 26;
}

