
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Feb 07 18:59:56 CET 2020
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Else = 12;
  public static final int C_par = 24;
  public static final int Out = 16;
  public static final int Numero = 4;
  public static final int A_llave = 25;
  public static final int Op_booleano = 5;
  public static final int Tipo = 2;
  public static final int Const = 13;
  public static final int PuntoYComa = 22;
  public static final int Coma = 20;
  public static final int Op_aritmetico = 7;
  public static final int Op_relacional = 9;
  public static final int In = 15;
  public static final int Main = 17;
  public static final int EOF = 0;
  public static final int C_llave = 26;
  public static final int If = 14;
  public static final int Return = 19;
  public static final int error = 1;
  public static final int Id = 3;
  public static final int Op_logico = 8;
  public static final int A_par = 23;
  public static final int Void = 21;
  public static final int Def = 18;
  public static final int Igual = 11;
  public static final int While = 10;
  public static final int String = 6;
}

