
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Feb 02 21:13:30 CET 2020
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Else = 5;
  public static final int C_par = 19;
  public static final int Out = 11;
  public static final int Numero = 6;
  public static final int Op_booleano = 25;
  public static final int A_llave = 20;
  public static final int Tipo = 7;
  public static final int Const = 8;
  public static final int Op_aritmetico = 22;
  public static final int PuntoYComa = 17;
  public static final int Coma = 15;
  public static final int Op_relacional = 24;
  public static final int In = 10;
  public static final int Main = 12;
  public static final int EOF = 0;
  public static final int C_llave = 21;
  public static final int If = 9;
  public static final int Return = 14;
  public static final int error = 1;
  public static final int Id = 4;
  public static final int Op_logico = 23;
  public static final int A_par = 18;
  public static final int Void = 16;
  public static final int Igual = 3;
  public static final int Def = 13;
  public static final int While = 2;
  public static final int String = 26;
}

